name: polymer_intl
description: An example of using Polymer with localized Intl messages
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  intl: '>=0.11.6 <0.12.0'
  polymer: '>=0.13.0 <0.14.0'
  unittest: any
transformers:
- polymer:
    entry_points: web/polymer_intl.html
