name: pop_pop_win
author: Dart Team <misc@dartlang.org>
description: '"Pop, Pop, Win!" is an implementation of Minesweeper in Dart.'
homepage: http://www.dartlang.org
environment:
  sdk: '>=1.3.0 <2.0.0'
dependencies:
  bot: '>=0.26.0 <0.28.0'
  browser: '>=0.10.0 <0.11.0'
  chrome: '>=0.6.3 <0.7.0'
  stagexl: '>=0.9.1 <0.11.0'
dev_dependencies:
  unittest: '>=0.10.0 <0.12.0'
