name: pop_pop_win
description: '"Pop, Pop, Win!" is an implementation of Minesweeper in Dart.'
environment:
  sdk: '>=1.3.0 <2.0.0'
dependencies:
  bot: '>=0.26.0 <0.27.0'
  browser: '>=0.10.0 <0.11.0'
  stagexl: '>=0.9.1 <0.11.0'
dev_dependencies:
  unittest: '>=0.10.0 <0.11.0'
